const vocab = [
    "der / die / das",
    "und",
    "sein",
    "in",
    "ein",
    "zu",
    "haben",
    "ich",
    "werden",
    "sie",
    "von",
    "nicht",
    "mit",
    "es",
    "sich",
    "auch",
    "auf",
    "für",
    "an",
    "er",
    "so",
    "dass",
    "können",
    "dies",
    "als",
    "ihr",
    "ja",
    "wie",
    "bei",
    "oder",
    "wir",
    "aber",
    "dann",
    "man",
    "da",
    "sein",
    "noch",
    "nach",
    "was",
    "also",
    "aus",
    "all",
    "wenn",
    "nur",
    "müssen",
    "sagen",
    "um",
    "über",
    "machen",
    "kein",
    "Jahr",
    "du",
    "mein",
    "schon",
    "vor",
    "durch",
    "geben",
    "mehr",
    "andere, anderer, anderes",
    "viel",
    "kommen",
    "jetzt",
    "sollen",
    "mir",
    "wollen",
    "ganz",
    "mich",
    "immer",
    "gehen",
    "sehr",
    "hier",
    "doch",
    "bis",
    "groß",
    "wieder",
    "Mal / mal",
    "zwei",
    "gut",
    "wissen",
    "neu",
    "sehen",
    "lassen",
    "uns",
    "weil",
    "unter",
    "denn",
    "stehen",
    "jede, jeder, jedes",
    "Beispiel",
    "Zeit",
    "erste, erster, erstes",
    "ihm",
    "ihn",
    "wo",
    "lang / lange",
    "eigentlich",
    "damit",
    "selbst, selber",
    "unser",
    "oben",
];
const vocabTranslations = [
    "the; that, those; who, that",
    "and",
    "to be; to have",
    "in; in the",
    "a, an; one (of)",
    "to, at; too",
    "to have; to have",
    "I",
    "to become; to become; to be",
    "she, her; they, them; you (formal)",
    "from, of",
    "not",
    "with",
    "it",
    "self",
    "also, too",
    "on, at, in",
    "for",
    "at, on; at/on the",
    "he",
    "so; thus, this way, such",
    "that",
    "can, to be able",
    "this, that",
    "as, when; than",
    "you, her; her, their, hers, theirs; your",
    "yes; certainly, really",
    "how; as",
    "by, with, at",
    "or",
    "we",
    "but",
    "then",
    "one, you",
    "there; because",
    "his, its",
    "still, yet",
    "after, toward",
    "what",
    "so, therefore",
    "out, out of, from",
    "all",
    "if, when",
    "only",
    "to have to, must",
    "to say",
    "around, at; in order to",
    "above, over, about",
    "to do, make",
    "no, not a/an",
    "year",
    "you",
    "my",
    "already",
    "in front of, before, ago",
    "through",
    "to give",
    "more",
    "other",
    "much, a lot, many",
    "to come",
    "now",
    "should, ought to",
    "me",
    "to want",
    "whole, all the; quite",
    "me",
    "always",
    "to go",
    "very",
    "here",
    "however, still",
    "until",
    "big, large, great",
    "again",
    "time; times (math); time(s); once; just",
    "two",
    "good",
    "to know",
    "new",
    "to see",
    "to let, allow, have (something) done",
    "us",
    "because",
    "under",
    "because",
    "to stand",
    "every, each",
    "example",
    "time",
    "first",
    "him, it",
    "him",
    "where",
    "long; for a long time",
    "actually; actual, real",
    "with it; so that",
    "self; even",
    "our",
    "above, up there"
];

const particle = [
    "(def. art.)",
    "(dem. pron.)",
    "(rel. pron)",
    "(conj.)",
    "(verb)",
    "(aux./perfect tense)",
    "(prep.)",
    "(indef. art.)",
    "(pron.)",
    "(art./pron.)",
    "(aux./future tense)",
    "(aux./passive voice)",
    "(adv.)",
    "(pron.)",
    "(poss. adj.)",
    "(num.)",
    "(noun)",
    "(adv./flavoring particle)",
    "(noun)",
    "(noun)",
    "(adv./flavoring particle)",
    "(adj.)",
    "(adj.)",
    "(adj.)",
    "(verb)",
    "(adj.)",
    "(adv./flavoring particle)",
    "(adj.)",
    "(adj.)",
    "(adj.)",
    "(verb)",
    "(adv./flavoring particle)",
    "(adj.)",
    "(adv./flavoring particle)",
    "(verb)",
    "(adj./pron.)",
    "(adj.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adj./pron.)",
    "(adj./pron.)",
    "(adj.)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(adj.)",
    "(num.)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(adj./pron.)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(adv.)",
    "(adj.)",
    "(adj./pron.)",
    "(noun)",
    "(noun)",
    "(noun)",
    "(adj./pron.)",
    "(noun)",
    "(noun)",
    "(adv./flavoring particle)",
    "(adj.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adj.)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(pron.)",
    "(pron.)",
    "(pron.)",
    "(adv.)",
    "(conj.)",
    "(adv.)",
    "(adv.)",
    "(conj.)",
    "(adv./flavoring particle)",
    "(verb)",
    "(pron.)",
    "(pron.)",
    "(conj.)",
    "(adv.)",
    "(verb)",
    "(verb)",
    "(adv.)",
    "(adv.)",
    "(adv.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adj./pron.)",
    "(adj./pron.)",
    "(adj./pron.)",
    "(num.)",
    "(adj.)",
    "(verb)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(pron.)",
    "(conj.)",
    "(adj./pron.)",
    "(noun)",
    "(noun)",
    "(noun)",
    "(adj./pron.)",
    "(noun)",
    "(noun)",
    "(adv./flavoring particle)",
    "(adj.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adj.)",
    "(adj.)",
    "(verb)",
    "(verb)",
    "(pron.)",
    "(pron.)",
    "(pron.)",
    "(adv.)",
    "(conj.)",
    "(adv.)",
    "(adv.)",
    "(conj.)",
    "(adv./flavoring particle)",
    "(verb)",
    "(pron.)",
    "(pron.)",
    "(conj.)",
    "(adv.)",
    "(verb)",
    "(verb)",
    "(adv.)",
    "(adv.)",
    "(adv.)",
    "(adj.)",
    "(adv.)",
    "(adj.)",
    "(adj./pron.)",
    "(adj./pron.)",
    "(adj./pron.)"

];

const audioURLs = [
    '/home/project2/vocab/vocabTTS/der_die_das.mp3',
    '/home/project2/vocab/vocabTTS/und.mp3',
    '/home/project2/vocab/vocabTTS/sein.mp3',
    '/home/project2/vocab/vocabTTS/in.mp3',
    '/home/project2/vocab/vocabTTS/ein.mp3',
    '/home/project2/vocab/vocabTTS/zu.mp3',
    '/home/project2/vocab/vocabTTS/haben.mp3',
    '/home/project2/vocab/vocabTTS/ich.mp3',
    '/home/project2/vocab/vocabTTS/werden.mp3',
    '/home/project2/vocab/vocabTTS/sie.mp3',
    '/home/project2/vocab/vocabTTS/von.mp3',
    '/home/project2/vocab/vocabTTS/nicht.mp3',
    '/home/project2/vocab/vocabTTS/mit.mp3',
    '/home/project2/vocab/vocabTTS/es.mp3',
    '/home/project2/vocab/vocabTTS/sich.mp3',
    '/home/project2/vocab/vocabTTS/auch.mp3',
    '/home/project2/vocab/vocabTTS/auf.mp3',
    '/home/project2/vocab/vocabTTS/für.mp3',
    '/home/project2/vocab/vocabTTS/an.mp3',
    '/home/project2/vocab/vocabTTS/er.mp3',
    '/home/project2/vocab/vocabTTS/so.mp3',
    '/home/project2/vocab/vocabTTS/dass.mp3',
    '/home/project2/vocab/vocabTTS/können.mp3',
    '/home/project2/vocab/vocabTTS/dies.mp3',
    '/home/project2/vocab/vocabTTS/als.mp3',
    '/home/project2/vocab/vocabTTS/ihr.mp3',
    '/home/project2/vocab/vocabTTS/ja.mp3',
    '/home/project2/vocab/vocabTTS/wie.mp3',
    '/home/project2/vocab/vocabTTS/bei.mp3',
    '/home/project2/vocab/vocabTTS/oder.mp3',
    '/home/project2/vocab/vocabTTS/wir.mp3',
    '/home/project2/vocab/vocabTTS/aber.mp3',
    '/home/project2/vocab/vocabTTS/dann.mp3',
    '/home/project2/vocab/vocabTTS/man.mp3',
    '/home/project2/vocab/vocabTTS/da.mp3',
    '/home/project2/vocab/vocabTTS/sein2.mp3',
    '/home/project2/vocab/vocabTTS/noch.mp3',
    '/home/project2/vocab/vocabTTS/nach.mp3',
    '/home/project2/vocab/vocabTTS/was.mp3',
    '/home/project2/vocab/vocabTTS/also.mp3',
    '/home/project2/vocab/vocabTTS/aus.mp3',
    '/home/project2/vocab/vocabTTS/all.mp3',
    '/home/project2/vocab/vocabTTS/wenn.mp3',
    '/home/project2/vocab/vocabTTS/nur.mp3',
    '/home/project2/vocab/vocabTTS/müssen.mp3',
    '/home/project2/vocab/vocabTTS/sagen.mp3',
    '/home/project2/vocab/vocabTTS/um.mp3',
    '/home/project2/vocab/vocabTTS/über.mp3',
    '/home/project2/vocab/vocabTTS/machen.mp3',
    '/home/project2/vocab/vocabTTS/kein.mp3',
    '/home/project2/vocab/vocabTTS/Jahr.mp3',
    '/home/project2/vocab/vocabTTS/du.mp3',
    '/home/project2/vocab/vocabTTS/mein.mp3',
    '/home/project2/vocab/vocabTTS/schon.mp3',
    '/home/project2/vocab/vocabTTS/vor.mp3',
    '/home/project2/vocab/vocabTTS/durch.mp3',
    '/home/project2/vocab/vocabTTS/geben.mp3',
    '/home/project2/vocab/vocabTTS/mehr.mp3',
    '/home/project2/vocab/vocabTTS/andere_anderer_anderes.mp3',
    '/home/project2/vocab/vocabTTS/viel.mp3',
    '/home/project2/vocab/vocabTTS/kommen.mp3',
    '/home/project2/vocab/vocabTTS/jetzt.mp3',
    '/home/project2/vocab/vocabTTS/sollen.mp3',
    '/home/project2/vocab/vocabTTS/mir.mp3',
    '/home/project2/vocab/vocabTTS/wollen.mp3',
    '/home/project2/vocab/vocabTTS/ganz.mp3',
    '/home/project2/vocab/vocabTTS/mich.mp3',
    '/home/project2/vocab/vocabTTS/immer.mp3',
    '/home/project2/vocab/vocabTTS/gehen.mp3',
    '/home/project2/vocab/vocabTTS/sehr.mp3',
    '/home/project2/vocab/vocabTTS/hier.mp3',
    '/home/project2/vocab/vocabTTS/doch.mp3',
    '/home/project2/vocab/vocabTTS/bis.mp3',
    '/home/project2/vocab/vocabTTS/groß.mp3',
    '/home/project2/vocab/vocabTTS/wieder.mp3',
    '/home/project2/vocab/vocabTTS/Mal_mal.mp3',
    '/home/project2/vocab/vocabTTS/zwei.mp3',
    '/home/project2/vocab/vocabTTS/gut.mp3',
    '/home/project2/vocab/vocabTTS/wissen.mp3',
    '/home/project2/vocab/vocabTTS/neu.mp3',
    '/home/project2/vocab/vocabTTS/sehen.mp3',
    '/home/project2/vocab/vocabTTS/lassen.mp3',
    '/home/project2/vocab/vocabTTS/uns.mp3',
    '/home/project2/vocab/vocabTTS/weil.mp3',
    '/home/project2/vocab/vocabTTS/unter.mp3',
    '/home/project2/vocab/vocabTTS/denn.mp3',
    '/home/project2/vocab/vocabTTS/stehen.mp3',
    '/home/project2/vocab/vocabTTS/jede_jeder_jedes.mp3',
    '/home/project2/vocab/vocabTTS/Beispiel.mp3',
    '/home/project2/vocab/vocabTTS/Zeit.mp3',
    '/home/project2/vocab/vocabTTS/erste_erster_erstes.mp3',
    '/home/project2/vocab/vocabTTS/ihm.mp3',
    '/home/project2/vocab/vocabTTS/ihn.mp3',
    '/home/project2/vocab/vocabTTS/wo.mp3',
    '/home/project2/vocab/vocabTTS/lang_lange.mp3',
    '/home/project2/vocab/vocabTTS/eigentlich.mp3',
    '/home/project2/vocab/vocabTTS/damit.mp3',
    '/home/project2/vocab/vocabTTS/selbst_selber.mp3',
    '/home/project2/vocab/vocabTTS/unser.mp3',
    '/home/project2/vocab/vocabTTS/oben.mp3',
];

const gridContainer = document.getElementById("gridContainer");

function createAudioClickHandler(audio) {
    return function () {
        audio.play();
    };
}

for (let i = 0; i < vocab.length; i++) {
    const gridItem = document.createElement("div");
    gridItem.className = "grid-item pointer";

    const audioIcon = document.createElement("img");
    audioIcon.src = "/home/project2/images/audio_icon.png"; 
    audioIcon.alt = "Audio Icon";
    audioIcon.className = "soundIcon";

    const particleText = document.createElement("div");
    particleText.textContent = particle[i];
    particleText.className = "smallerText right";

    const vocabWord = document.createElement("div");
    vocabWord.textContent = vocab[i];
    vocabWord.className = "largerText";

    const vocabTranslation = document.createElement("div");
    vocabTranslation.textContent = vocabTranslations[i];
    vocabTranslation.className = "smallerText";

    const audioElement = document.createElement("audio");
    audioElement.src = audioURLs[i];

    audioElement.className = "sound";

    gridItem.addEventListener("click", createAudioClickHandler(audioElement));

    
    gridItem.appendChild(particleText);
    gridItem.appendChild(vocabWord);
    gridItem.appendChild(vocabTranslation);
    gridItem.appendChild(audioElement);
    gridItem.appendChild(audioIcon);

    gridContainer.appendChild(gridItem);
}